---
kind: Agent
apiVersion: agent.k8s.elastic.co/v1alpha1
metadata:
  name: agent-otel-apm
  namespace: elastic
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  version: 8.17.1
  elasticsearchRefs:
    - name: elasticsearch # Reference to the Elasticsearch cluster managing APM data
      namespace: elastic
  deployment:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        # securityContext:
        #   runAsUser: 0
        #   # privileged: true
        # volumes:
        # - name: agent-data
        #   emptyDir: {}
        containers:
        - name: agent
          securityContext:
            runAsUser: 0
            privileged: true
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
  config:
    inputs:
      # - name: system-alvaro
      #   revision: 1
      #   type: system/metrics
      #   use_output: default
      #   meta:
      #     package:
      #       name: system
      #       version: 0.9.1
      #   data_stream:
      #     namespace: default
      #   streams:
      #     - id: system/metrics-system.cpu
      #       data_stream:
      #         dataset: system.cpu
      #         type: metrics
      #       metricsets:
      #         - cpu
      #       cpu.metrics:
      #         - percentages
      #         - normalized_percentages
      #       period: 10s
      # Collect application traces: Collect application traces
      - id: otel-apm
        revision: 1
        type: apm
        apm-server:
          auth:
            anonymous:
              enabled: true
              allow_agent:
                - rum-js
                - js-base
                - iOS/swift
              rate_limit:
                event_limit: 300
                ip_limit: 1000
              # allow_service:
              #  - <ANONYMOUS_ALLOW_SERVICE> # undefined
            api_key:
              limit: 100
              # enabled: <API_KEY_ENABLED> # undefined
            # secret_token: <SECRET_TOKEN> # undefined
          capture_personal_data: true
          idle_timeout: 45s
          host: 'localhost:8200'
          max_event_size: 307200
          max_header_size: 1048576
          read_timeout: 3600s
          response_headers: null
          java_attacher:
            discovery-rules: null
            # enabled: <JAVA_ATTACHER_ENABLED> # undefined
            # download-agent-version: <JAVA_ATTACHER_AGENT_VERSION> # undefined
          rum:
            enabled: true
            allow_origins:
              - '*'
            exclude_from_grouping: ^/webpack
            library_pattern: node_modules|bower_components|~
            response_headers: null
            # allow_headers:
            #  - <RUM_ALLOW_HEADERS> # undefined
          shutdown_timeout: 30s
          ssl:
            key_passphrase: null
            supported_protocols:
              - TLSv1.2
              - TLSv1.3
            # enabled: true # undefined
            # certificate: <TLS_CERTIFICATE> # undefined
            # key: <TLS_KEY> # undefined
            # cipher_suites:
            #  - <TLS_CIPHER_SUITES> # undefined
            # curve_types:
            #  - <TLS_CURVE_TYPES> # undefined
          write_timeout: 30s
          sampling:
            tail:
              interval: 1m
              policies:
                - sample_rate: 0.1
              storage_limit: 3GB
              # enabled: <TAIL_SAMPLING_ENABLED> # undefined
          # default_service_environment: <DEFAULT_SERVICE_ENVIRONMENT> # undefined
          # expvar.enabled: <EXPVAR_ENABLED> # undefined
          # pprof.enabled: <PPROF_ENABLED> # undefined
          # max_connections: <MAX_CONNECTIONS> # undefined
