---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: otel-elk
  name: otel-elk
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  project: default
  source:
    path: otel-collector
    repoURL: https://github.com/alvarolop/otel-to-elk.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
