---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-quarkus-observability
  namespace: kafka
  labels:
    strimzi.io/cluster: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  topicName: tracing.quarkus-observability
  # ...