---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams-console
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: amq-streams-console
  source: redhat-operators
  sourceNamespace: openshift-marketplace
